version: "3"
services:
  app:
    build: ./
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      PORT: 5000
    ports:
      - 80:5000

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
